import { Fixture } from '@/types';

// Omit 'id' and 'createdAt' as they will be generated by Firestore
export const seedFixtures: Omit<Fixture, 'id' | 'createdAt'>[] = [
  // 2025-26 Season

  // August 2025
  { date: '2025-08-31', time: '07:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'West Ham', venue: 'Home' },

  // September 2025
  { date: '2025-09-13', time: '07:00', competition: 'Premier League', homeTeam: 'Arsenal', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2025-09-18', time: '12:00', competition: 'EFL Cup', homeTeam: 'Swansea', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2025-09-20', time: '15:00', competition: 'Premier League', homeTeam: 'Burnley', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2025-09-24', time: '20:00', competition: 'Europa League', homeTeam: 'Real Betis', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2025-09-28', time: '17:30', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Sunderland', venue: 'Home' },

  // October 2025
  { date: '2025-10-02', time: '20:00', competition: 'Europa League', homeTeam: 'Nottm Forest', awayTeam: 'FC Midtjylland', venue: 'Home' },
  { date: '2025-10-05', time: '14:00', competition: 'Premier League', homeTeam: 'Newcastle', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2025-10-18', time: '12:30', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Chelsea', venue: 'Home' },
  { date: '2025-10-23', time: '20:00', competition: 'Europa League', homeTeam: 'Nottm Forest', awayTeam: 'FC Porto', venue: 'Home' },
  { date: '2025-10-26', time: '15:00', competition: 'Premier League', homeTeam: 'Bournemouth', awayTeam: 'Nottm Forest', venue: 'Away' },

  // November 2025
  { date: '2025-11-02', time: '16:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Man Utd', venue: 'Home' },
  { date: '2025-11-06', time: '18:45', competition: 'Europa League', homeTeam: 'Sturm Graz', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2025-11-09', time: '15:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Leeds', venue: 'Home' },
  { date: '2025-11-23', time: '16:00', competition: 'Premier League', homeTeam: 'Liverpool', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2025-11-27', time: '20:00', competition: 'Europa League', homeTeam: 'Nottm Forest', awayTeam: 'Malmö FF', venue: 'Home' },
  { date: '2025-11-30', time: '15:05', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Brighton', venue: 'Home' },

  // December 2025
  { date: '2025-12-03', time: '21:00', competition: 'Premier League', homeTeam: 'Wolves', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2025-12-07', time: '16:00', competition: 'Premier League', homeTeam: 'Everton', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2025-12-11', time: '18:45', competition: 'Europa League', homeTeam: 'FC Utrecht', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2025-12-14', time: '16:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Tottenham', venue: 'Home' },
  { date: '2025-12-21', time: '16:00', competition: 'Premier League', homeTeam: 'Fulham', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2025-12-26', time: '16:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Man City', venue: 'Home' },
  { date: '2025-12-31', time: '21:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Everton', venue: 'Home' },

  // January 2026
  { date: '2026-01-04', time: '16:00', competition: 'Premier League', homeTeam: 'Aston Villa', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2026-01-08', time: '21:00', competition: 'Premier League', homeTeam: 'West Ham', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2026-01-18', time: '16:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Arsenal', venue: 'Home' },
  { date: '2026-01-22', time: '21:00', competition: 'Europa League', homeTeam: 'Braga', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2026-01-25', time: '16:00', competition: 'Premier League', homeTeam: 'Brentford', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2026-01-29', time: '21:00', competition: 'Europa League', homeTeam: 'Nottm Forest', awayTeam: 'Ferencvaros', venue: 'Home' },

  // February 2026
  { date: '2026-02-01', time: '16:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Crystal Palace', venue: 'Home' },
  { date: '2026-02-08', time: '16:00', competition: 'Premier League', homeTeam: 'Leeds', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2026-02-11', time: '21:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Wolves', venue: 'Home' },
  { date: '2026-02-22', time: '16:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Liverpool', venue: 'Home' },

  // March 2026
  { date: '2026-03-01', time: '16:00', competition: 'Premier League', homeTeam: 'Brighton', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2026-03-04', time: '21:00', competition: 'Premier League', homeTeam: 'Man City', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2026-03-15', time: '16:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Fulham', venue: 'Home' },
  { date: '2026-03-22', time: '16:00', competition: 'Premier League', homeTeam: 'Tottenham', awayTeam: 'Nottm Forest', venue: 'Away' },

  // April 2026
  { date: '2026-04-11', time: '15:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Aston Villa', venue: 'Home' },
  { date: '2026-04-18', time: '15:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Burnley', venue: 'Home' },
  { date: '2026-04-25', time: '15:00', competition: 'Premier League', homeTeam: 'Sunderland', awayTeam: 'Nottm Forest', venue: 'Away' },

  // May 2026
  { date: '2026-05-02', time: '15:00', competition: 'Premier League', homeTeam: 'Chelsea', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2026-05-09', time: '15:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Newcastle', venue: 'Home' },
  { date: '2026-05-17', time: '15:00', competition: 'Premier League', homeTeam: 'Man Utd', awayTeam: 'Nottm Forest', venue: 'Away' },
  { date: '2026-05-25', time: '16:00', competition: 'Premier League', homeTeam: 'Nottm Forest', awayTeam: 'Bournemouth', venue: 'Home' },
];
